backend:
  name: github
  repo: your-github-username/your-repo-name # IMPORTANT: Placeholder
  branch: main

media_folder: "static/images/uploads"
public_folder: "/static/images/uploads"

collections:
  - name: "pages"
    label: "Page Content"
    files:
      - label: "Homepage"
        name: "home"
        file: "_data/content.json"
        fields:
          - { label: "Main Headline", name: "main_headline", widget: "string" }
          - { label: "About Us Text", name: "about_us_text", widget: "text" }
          - label: "Core Services"
            name: "core_services"
            widget: "list"
            fields:
              - { label: "Service Name", name: "name", widget: "string" }
              - { label: "Service Description", name: "description", widget: "text" }
          - label: "Why Choose Us Points"
            name: "why_choose_us_points"
            widget: "list"
            fields:
              - { label: "Point", name: "point", widget: "string" }
          - label: "Reviews"
            name: "reviews"
            widget: "list"
            fields:
              - { label: "Quote", name: "quote", widget: "text" }
              - { label: "Customer Name", name: "customer_name", widget: "string" }
              - { label: "Rating (1-5)", name: "rating", widget: "number" }
          - { label: "Contact Phone", name: "contact_phone", widget: "string" }
          - { label: "Contact Address", name: "contact_address", widget: "string" }